config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :contacts, only: [:new, :create]

  get '/about', to: 'static_pages#about', as: 'about'

  get '/work', to: 'static_pages#work', as: 'work'

  get '/chorehero', to: 'static_pages#chorehero', as: 'chorehero'

  get '/svj_photography', to: 'static_pages#svj_photography', as: 'svj_photography'

  get '/my_blog', to: 'static_pages#my_blog', as: 'my_blog'

  get '/whats_on_your_agenda', to: 'static_pages#whats_on_your_agenda', as: 'whats_on_your_agenda'

  get '/linkage', to: 'static_pages#linkage', as: 'linkage'

  get '/wizard_of_rails', to: 'static_pages#wizard_of_rails', as: 'wizard_of_rails'

  get '/spectrum_games', to: 'static_pages#spectrum_games', as: 'spectrum_games'

  get '/sinatra_calculator', to: 'static_pages#sinatra_calculator', as: 'sinatra_calculator'

  get '/my_first_website', to: 'static_pages#my_first_website', as: 'my_first_website'

  get '/first_landing_page', to: 'static_pages#first_landing_page', as: 'first_landing_page'

  get '/twopeace', to: 'static_pages#twopeace', as: 'twopeace'

  get '/rag', to: 'static_pages#rag', as: 'rag'

  get '/highscore', to: 'static_pages#highscore', as: 'highscore'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "Portfolio Contact Form",
      :to => "scot.c.chard@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/create.html.erb
<div class="grid-container">
  <div class="row">
    <div class="main_home">
      <div class="col-2">
        <h1 id='thanks_header'> Thank You For Contacting Me!</h1>
        <p id='thanks_para'> I will be in touch with you soon.</p>
      </div>
    </div>
  </div>
</div>  

app/views/contacts/new.html.erb
<div class="grid-container">
  <div class="row">
    <div class="about_home">
      <div class="col-2">
        <img src="http://olivermanalese.com/wp-content/uploads/2016/02/Contact-Me.jpg" class="contact_img animated swing"/>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-2">
      <div class="contact_form">

        <p id="contact_header">Interested? Send Me an Email!</p>

        <%= form_for @contact do |f| %>
        
        <%= f.text_field :name, :class => "contact_input", :placeholder => "Name*", required: true %>
        <br/>
        <%= f.email_field :email, :class => "contact_input", :placeholder => "Email*", required: true %>
        <br/>
        <%= f.text_area :message, :id => "message", :placeholder => "Leave Me a Message!", as: :text %>
        <br/>
        <div class="hidden">
          <%= f.label :nickname, :class => "contact_labels" %><br>
          <%= f.text_field :nickname, :class => "contact_input", hint: 'leave this field blank' %>
        </div> 

        <%= f.submit 'Send Message', class: "submit_btn" %>
      <% end %>
      </div> 
    </div>
  </div>
</div>    

     

app/views/layouts/_footer.html.erb
<div class="grid-container">
  <div class="row">
    <div id='footer'>
      <div class="footer-links">
        <%= link_to 'Home', root_path, :class => 'links' %>
        <%= link_to 'About', about_path, :class => 'links' %>
        <%= link_to 'Work', work_path, :class => 'links' %>
        <%= link_to 'Contact', new_contact_path, :class => 'links' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="grid-container">
  <div class="row">
    <div class="nav">
      <div class="header-links">
        <%= link_to 'Home', root_path, :class => 'links' %>
        <%= link_to 'About', about_path, :class => 'links' %>
        <%= link_to 'Work', work_path, :class => 'links' %>
        <%= link_to 'Contact', new_contact_path, :class => 'links' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Raleway: 400, 200' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="http://s.mlcdn.co/animate.css">
</head>
<body>
  <header>
    <%= render 'layouts/navbar' %>
  </header>

<%= yield %>
    <%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/about.html.erb
<div class="grid-container">
  <div class="row">
    <div class="home">
      <div id='about-text'>
        <img id='about_img' src='about_me.png'/> 
        <h2 id="about_header" class="animated flipInY"> Hi I am Scot Chard </h2>
        <p class="about_text animated bounceInUp"> I currently am a Jr. Front End Developer at <a href="https://mooreandscarry.com/" target="_blank">Moore and Scarry Advertising</a> </p>
        <p class="about_text animated bounceInUp"> My goal is to become a Full Stack Ruby on Rails Developer </p>
        <a href="https://github.com/Scotchard22" target="_blank"><img class="social_icons" src="github.png"/></a>
        <a href="https://www.linkedin.com/in/scotchard" target="_blank"><img class="social_icons" src="linkedin.png"/></a>
        <a href="https://www.instagram.com/scot_chard/" target="_blank"><img class="social_icons" src="insta.png"/></a>
      </div>
      <div class="row">  
        <div class="col-2">
          <a href="https://drive.google.com/file/d/0B1tf_RhC0O42N2h2QVc3dV9CUmc/view?usp=sharing" target="_blank" class="about_btn">View My Resume</a>

        </div>  
      </div> 
    </div>
  </div>

  <div class="row">
    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">About Me</h2>
        <p class="about_para">Welcome to my portfolio!</p>
        <p class="list_items">Okay so a little bit about myself, I currently am a Jr. Front End Developer at <a href="https://mooreandscarry.com/" target="blank">Moore and Scarry</a>. My journey to become a Full Stack Ruby on Rails Developer started in August, 2015. Ruby on Rails is my passion and exactly what I want to do in a Full Time role. I went through a Full-Immersive coding bootcamp that had taught us Full Stack Ruby on Rails, and I was instantly hooked. I've built many Ruby of Rails projects. I continue to teach myself new things everyday with the hopes of becoming a Full Time Ruby on Rails Developer. I am very dedicated to my work and also very proud to be where I am today! If you're looking for a bright, dedicated, and passionate Ruby on Rails Developer please shoot me an email! Thanks!</p>
      </div> 
    </div> 
    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Work History</h2>
        <p class="text_para">Moore and Scarry Advertising: June, 2016 - Present</p>
          <li class="list_items">Build and maintain client websites, and landing pages</li>
          <li class="list_items">I take our designed webpages and I transfer it into HTML5, CSS3</li>
          <li class="list_items">We colloaborate closely with the Designers and Copywrite teams</li>
        <p class="text_para">Rite Aid: Feb, 2014 - May, 2016</p>
          <li class="list_items">Worked as a Pharmacy Technician for a little over 2 years</li>
          <li class="list_items">Perform routine tasks such as counting pills and typing scripts</li>
          <li class="list_items">Assist licensed pharmacists dispense prescription medication</li>
      </div> 
    </div> 
  </div>
  <div class="row">
    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Skills</h2>
        <div class="col-3">
          <p class="skill_para">Ruby on Rails</p>
          <p class="skill_para">HTML5</p>
          <p class="skill_para">CSS3</p>
          <p class="skill_para">Javascript/jQuery</p>
        </div>
        <div class="col-3">
          <p class="skill_para">Git/Github</p>
          <p class="skill_para">ERB</p>
          <p class="skill_para">HAML</p>
          <p class="skill_para">Responsive Web Design</p>
        </div>
      </div> 
    </div> 
    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Education</h2>
        <p class="text_para"> DevPoint Labs: Aug, 2015 - Nov, 2015</p>
        <p class="list_items">Devpoint Labs is a Full Immersive 11 week course that takes entry level performers and prepares them for a Jr. Developer position.</p>
        <p class="list_items">They offer courses in full-stack Ruby on Rails, full-stack JavaScript and UX Design.</p></br>
        <p class="list_items"> Studies include:</br> Ruby, Rails, Javascript, CSS, HTML, jQuery, AJAX, Coffeescript, Command Line, Git, Github, Ruby Gems, Pair Programming, TDD, BDD, Rspec, APIs, and more!</p>
        <p class="list_items">Check them out - <a href="http://www.devpointlabs.com/" target="_blank">DevPoint Labs</a></p>
      </div> 
    </div> 
  </div>
</div>

app/views/static_pages/chorehero.html.erb
<div class="grid-container">
  <div class="row">
    <div class="home">
      <div class="col-2">
        <img class="slideshow-img" src='chorehero.png'/>
      </div>
      <div class="slide_title_border col-2">
        <h2 class="slide_title">Chore Hero</h2>
      </div>
    </div>
  </div>  
  
  <div class="row">
    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Description</h2>
        <p class="text_para">ChoreHero is a web app that gamifies chores for children. They earn XP for doing chores which can be traded in for prizes and fun activities. As a team we planned out our days, workflow and maintained a good pace with the project. We had daily scrum meetings and followed agile methods. We incorporated many ruby gems and rails techniques in the project. You can visit the website live at <a href="http://www.chorehero.us/" target="_blank">www.chorehero.us</a></p>
      </div> 
    </div>  

    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Tech Stack</h2>
        <p class="text_para">The tech stack used to create ChoreHero was Full Stack Ruby on Rails. To be more specific, we used Ruby for our backend, as well as the framework Rails. Instead of the usual ERB we switched it up, and used the preprocessor HAML in replace of ERB. Our front end programming languages were HTML5, CSS3, Javascript and Javascript's preprocessor Coffeescript which blends perfectly with the Rails framework.</p>
      </div> 
    </div>  
  </div>

  <div class="row">
    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Motive</h2>
        <p class="text_para">ChoreHero was actually an idea that 4 other team members and I created. Our team leader pitched an idea that we loved, and we built a plan to execute the idea. I was attending a coding bootcamp at the time. A week before the coding camp ended the class split into groups, and pitched ideas to eachother. Each group had to build a final project to present in the last week of the course.</p>
      </div>  
    </div> 

    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Something Kewl</h2>
        <p class="text_para">One thing that I am really proud about is our testing suite. We managed to reach a testing coverage of 88.65% for our whole application. A teammate and myself worked on the testing. We followed the rules of BDD, Behavior Driven Development. We tested our application with RSpec, which is a Ruby gem that was inspired by JBehave. Click here to learn about RSpec. <a href="http://rspec.info/" target="_blank">www.rspec.info</a></p>
      </div>   
    </div>
  </div>
</div>

<!-- 
  <div class="diy-slideshow">
    <figure class="show">
      <span class="prev">&laquo;</span>
      <img src="chorehero.jpg" width="100%" class="slideshow_img" /> 
      <span class="next">&raquo;</span>
    </figure>
     <figure>
      <img src="chorehero.jpg" width="100%" class="slideshow_img" />
    </figure>
    <figure>
      <img src="chorehero.jpg" width="100%" class="slideshow_img" /> 
    </figure>
  </div>  

</div>

<script>
      (function(){

var counter = 0, // to keep track of current slide
   $items = document.querySelectorAll('.diy-slideshow figure'), // a collection of all of the slides, caching for performance
   numItems = $items.length; // total number of slides

// this function is what cycles the slides, showing the next or previous slide and hiding all the others
var showCurrent = function(){
 var itemToShow = Math.abs(counter%numItems);// uses remainder (aka modulo) operator to get the actual index of the element to show  

 // remove .show from whichever element currently has it 
 // http://stackoverflow.com/a/16053538/2006057
 [].forEach.call( $items, function(el){
   el.classList.remove('show');
 });

 // add .show to the one item that's supposed to have it
 $items[itemToShow].classList.add('show');    
};

// add click events to prev & next buttons 
document.querySelector('.next').addEventListener('click', function() {
    counter++;
    showCurrent();
 }, false);

document.querySelector('.prev').addEventListener('click', function() {
    counter--;
    showCurrent();
 }, false);

})(); 
    </script> -->

app/views/static_pages/first_landing_page.html.erb
<div class="grid-container">
  <div class="row">
    <div class="home">
      <div class="col-2">
        <img class="slideshow-img" src='landing-page.png'/>
      </div>
      <div class="slide_title_border col-2">
        <h2 class="slide_title">Built My First Landing Page</h2>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Description</h2>
        <p class="text_para">This landing page earned me my first job as a developer. I was interviewing with a company called Moore and Scarry. They wanted to test my skills and sent me this test project to do. It was not difficult to me, and I was happy with the final product. Needless to say, the company was very happy with the outcome, and offered me the job. I accepted, and I am now a Jr. Front End Developer at Moore and Scary! </p>
      </div> 
    </div>  

    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Tech Stack</h2>
        <p class="text_para">Back to the basics!<br/> This website was built only using HTML5, and CSS3 !</p>
      </div> 
    </div>  
  </div>

  <div class="row">
    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Motive</h2>
        <p class="text_para">My reasoning behind building this landing page was to show off my skills and hopefully land a job. I previously had an interview with a company, and I was in round 2 of the interviewing process. The company provided me with a PSD file, (a photoshop image), and I had to transfer the image into a working HTML5, CSS3 web page. I then got started. It took me a few hours, but the final product turned out great.</p>
      </div>  
    </div> 

    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Something Kool</h2>
        <p class="text_para">I Landed the Job!! A few days after I had sent in my finished product I had recieved a phone call. It was the company. They had explained to me that they were really impressed with the finished product, and wanted to bring me on board! I accepted their offer, and landed my first job in the field! From writing my first line of code to landing my first job in the field was a huge accomplishment considering it had only taken me under a year !</p>
      </div>   
    </div>
  </div>
</div>

app/views/static_pages/highscore.html.erb
<div class="grid-container">
  <div class="row">
    <div class="home">
      <div class="col-2">
        <img class="slideshow-img" src='steve.png'/>
      </div>
      <div class="slide_title_border col-2">
        <h2 class="slide_title">No Internet = HIGH SCORE!</h2>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-2">
      <div class="text_boxes">
        <h2 class="text_header">Description</h2>
        <p class="text_para">What do you do when using Google Chrome, and you lose internet? Obviously you start playing Googles Hidden Dinosaur Game! On this day I had lost my internet due to a heavy storm passing by. This actually turned out to be great because it had given me the chance to get a HIGH SCORE of 3571! Don't worry my internetless friends, Google Chrome is here to save the day.</p>
      </div> 
    </div> 
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="grid-container">
  <div class="row">
    <div class='main_home'>
      <div id='header-text'>
        <img id='header-image' src='scot_prof.png'/> 
        <h1 id='title' class="animated zoomInRight">Scot Chard</h1>
        x x <hr> x
        <p id='subtitle' class="animated zoomInLeft">Jr. Front End Developer</p>
      </div>  
      <div class="row">  
        <div class="col-2">
          <a href="about" class="btn_1">About Me</a>
          <a href="work" class="btn_2">View My Work</a>
        </div>  
      </div>  
    </div>
  </div>
</div>

  

app/views/static_pages/linkage.html.erb
<div class="grid-container">
  <div class="row">
    <div class="home">
      <div class="col-2">
        <img class="slideshow-img" src='linkage.png'/>
      </div>
      <div class="slide_title_border col-2">
        <h2 class="slide_title">Linkage</h2>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Description</h2>
        <p class="text_para">Linkage is a link aggregator web application. Linkage is intended to be a place where people can come, and share links to funny videos, good blogs, or pretty much anything they find interesting on the internet. Users who signup can post their own links, edit their links, delete them, and even give a breif overview about why they are posting the link. Check out the code - <a href="https://github.com/Scotchard22/Linkage">Linkage</a></p>
      </div> 
    </div>  

    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Tech Stack</h2>
        <p class="text_para">The tech stack used to create Linkage was Full Stack Ruby on Rails. To be more specific, I used Ruby for the backend, which was matched with Rails for the framework. The front end programming languages used were HTML5, CSS3, and Javascript.</p>
      </div> 
    </div>  
  </div>

  <div class="row">
    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Motive</h2>
        <p class="text_para">My motivation for creating Linkage came from <a href="https://www.reddit.com/">reddit</a>. reddit went from a second tier aggregator site to taking over the internet. reddit gets millions of users on their site daily. It inspired me to make my own aggregator web application, and see if it would gain any traction.  </p>
      </div>  
    </div> 

    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Something Kool</h2>
        <p class="text_para">Something that I am proud of is the authentication Linkage has. I used the Devise Ruby gem for aunthentication. Users can sign up and sign in. Only users who sign up can create posts. With the authentication, the postgres database stores all of the users data, and assigns the user an ID. Only the user who created the post can go in, and choose to edit or delete the post due to having the same ID. </p>
      </div>   
    </div>
  </div>
</div>

app/views/static_pages/my_blog.html.erb
<div class="grid-container">
  <div class="row">
    <div class="home">
      <div class="col-2">
        <img class="slideshow-img" src='blog.png'/>
      </div>
      <div class="slide_title_border col-2">
        <h2 class="slide_title">My Personal Blog</h2>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Description</h2>
        <p class="text_para">Since it is my personal blog, I can add personal touches to it, and make it reflect my personality. I wanted to create a blog from scratch, because why not? It is awesome! I also wanted to stay away from easy, generic, and boring WordPress templates because I am a developer, and develop my applications from scratch! Check it out here - <a href="https://github.com/Scotchard22/My_Blog" target="_blank"> My Blog</a></p>
      </div> 
    </div>  

    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Tech Stack</h2>
        <p class="text_para">The tech stack used to create my personal blog was Full Stack Ruby on Rails. To be more specific, I used Ruby for the backend, which was matched with Rails for the framework. The front end programming languages used were HTML5, CSS3, and Javascript.</p>
      </div> 
    </div>  
  </div>

  <div class="row">
    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Motive</h2>
        <p class="text_para">The goal for creating a personal blog was to enhance my online presence, and create more social media for myself. I am going to be posting about my career path to becoming a Full-Stack Developer. I want to post about subjects I am currently learning, projects I am currently working on, and what I want to be learning in the near future.</p>
      </div>  
    </div> 

    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Something Kool</h2>
        <p class="text_para">A really cool feature I added to my personal blog was a ruby gem called Devise. Devise is for authentication purposes. I used the Devise ruby gem so that I could set myself as the admin of the application, and only I will be able to login, and access full functionality of my blog.</p>
      </div>   
    </div>
  </div>
</div>

app/views/static_pages/my_first_website.html.erb
<div class="grid-container">
  <div class="row">
    <div class="home">
      <div class="col-2">
        <img class="slideshow-img" src='first-website.png'/>
      </div>
      <div class="slide_title_border col-2">
        <h2 class="slide_title">My First Website</h2>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Description</h2>
        <p class="text_para">I have come a very long way since I built this website. This was at the beginning of my journey to become a full stack developer. I went through as many tutorials on HTML5, and CSS3 as possible. I picked it up very quickly, and was absolutely thrilled when I wrote my first line of code. From creating a simple "Hello World" webpage, to this very nice looking website.</p>
      </div> 
    </div>  

    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Tech Stack</h2>
        <p class="text_para">Back to the basics!<br/> This website was built only using HTML5, and CSS3 !</p>
      </div> 
    </div>  
  </div>

  <div class="row">
    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Motive</h2>
        <p class="text_para">What had initiated my interest in software was when I was scavenging around Youtube, and came across an interesting video. A 16 year old boy had built an application that summarized news articles. The teenager sold the application to Yahoo for 30 million dollars. Check out the video here - <a href="https://www.youtube.com/watch?v=gtjW6odrvz0">Summly</a>. I then began my research, came across web development, and here I am today!</p>
      </div>  
    </div> 

    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Something Kool</h2>
        <p class="text_para">This was my very first webpage! Can you believe that? This website had only taken me about an hour. I learned, and picked up HTML5 and CSS3 super fast in such a short amount of time. I was very excited, and proud after building the site. On the first day of the coding bootcamp I had attended, I showed this website to the class, and everyone was very impressed. They were not expecting any of our websites to look as good as this does.</p>
      </div>   
    </div>
  </div>
</div>

app/views/static_pages/rag.html.erb
<div class="grid-container">
  <div class="row">
    <div class="home">
      <div class="col-2">
        <img class="slideshow-img" src='rag.png'/>
      </div>
      <div class="slide_title_border col-2">
        <h2 class="slide_title">R.A.G</h2>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Description</h2>
        <p class="text_para">R.A.G - Random Adventure Generator. Home alone on a weekend? Nobody to hangout with? Nothing to do? Well to heck with boredom! You never have to be bored again! R.A.G is here to provide you with countless numbers of random adventures, and unlimited fun. Grab a friend, bring your goldfish, or go solo it's your choice! R.A.G provides you with a random location. The goal? Get to that location!  </p>
      </div> 
    </div>  

    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Tech Stack</h2>
        <p class="text_para">The tech stack used to create our Random Adventure Generator was Full Stack Ruby on Rails. To be more specific, we used Ruby for the backend, which was matched with Rails for the framework. The front end programming languages used were HTML5, CSS3, and bootstrap for a front end framework.</p>
      </div> 
    </div>  
  </div>

  <div class="row">
    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Motive</h2>
        <p class="text_para">HACKATHON! At the coding bootcamp I was attending we had hosted 2 hackathons. This was our first hackathon. Each team consisted of 4 people. 8 hours given to us as well as some preparation time before the hackathon started. My team started brainstorming, and pitching ideas for us to build. We all loved the outdoors, and came up with a fun way to get out more. Preparation time is up. Let the hackathon begin! </p>
      </div>  
    </div> 

    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Something Kool</h2>
        <p class="text_para">To determine the location given, we had used a Ruby gem called <a href="http://www.rubygeocoder.com/">Geocoder</a> - Check it out! The gem determines a location based on a street address or coordinates. We also implemented the Google Maps API that shows the user their given location. I also believe we came in 3rd place in the hackathon, which was very exciting!  </p>
      </div>   
    </div>
  </div>
</div>

app/views/static_pages/sinatra_calculator.html.erb
<div class="grid-container">
  <div class="row">
    <div class="home">
      <div class="col-2">
        <img class="slideshow-img" src='sin-calc.png'/>
      </div>
      <div class="slide_title_border col-2">
        <h2 class="slide_title">Sinatra Calculator</h2>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Description</h2>
        <p class="text_para">This is my first ever web application!<br/> This was a big stepping stone, and the beginning of how I got to be where I am now in my career! This web application carved the path for me to learn the Rails framework. It was very exciting to take a simple calculator program that ran only on my computer, and transform it into a functional web application!</p>
      </div> 
    </div>  

    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Tech Stack</h2>
        <p class="text_para">This web application was built using Sinatra (a Ruby framework, comparable to Rails). Also incorporated in this project was Ruby, HTML5, and CSS3 !</p>
      </div> 
    </div>  
  </div>

  <div class="row">
    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Motive</h2>
        <p class="text_para">The goal of this project was to gain an understanding of web frameworks, and why we use them. Earlier in the coding bootcamp we learned the Ruby programming language. With Ruby, we had scripted functional calculator programs. We wanted to take our programs and transform them into our first web application. Before, the only way to use our calculator programs was on the terminal on our local computers.</p>
      </div>  
    </div> 

    <div class="col-1">
      <div class="text_boxes">
        <h2 class="text_header">Something Kool</h2>
        <p class="text_para">I learned, and used the Sinatra framework as a stepping stone to learn the Rails framework. In the coding bootcamp I attended, they taught us Sinatra before teaching us Rails. They did this to help us get a feel of exactly what a web framework is. It had really helped me grasp, and understand the fundamentals of web frameworks!</p>
      </div>   
    </div>
  </div>
</div>